### ISSUE TITLE
Switch back to system package?

### ISSUE THREAD

**Issue by elwerene** [monosoul/wireplumber-rpm-with-fixes#1]
Hi, thanks for your package. If I saw it right in the original issue (https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/152) it is now fixed in the fedora package. How would I switch back to that?

Thanks :)

**Comment by monosoul** [comment]
Hey @elwerene , you don't really have to do anything, the current official wireplumber package is pretty much the same as this one (except for [this patch](https://github.com/monosoul/wireplumber-rpm-with-fixes/blob/main/0005-bluez-use-device-id-instead-of-profile-name-in-node-names.patch)). Once there is a newer official package available it will automatically replace the one from this COPR. 

But if you do eagerly want to switch to the official package, you can do this:
```shell
sudo dnf install wireplumber-0.4.11-3.fc36
sudo dnf copr remove monosoul/wireplumber-high-cpu-usage-fix
sudo dnf update --refresh
```

**Comment by elwerene** [comment]
Thank you! :)
